# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_detail', models.CharField(max_length=500)),
                ('long_detail', models.TextField()),
                ('image', models.FileField(upload_to=b'')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
