# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20161217_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='long_detail',
            field=models.TextField(blank=True),
        ),
    ]
